### ISSUE TITLE
League admin tools missing

### ISSUE THREAD

**Issue by climu** [climu/openstudyroom#18]
We need to create some views that allow league admins to view/edit/delete games, events, divisions, and players.

**Comment by rocqua** [comment]
Have you looked at the django admin interface? That should set-up deletion of these entries.

However, deletion of games, and even more so players, takes work to maintain consistency.
Deleting a game means updating the nb_loss and nb_wins on the players. (as well as results, though I have a proposal on reddit to make that automatic.) These could be solved by getting nb_loss from the database implicitly, rather than storing it explicitly for a player. (In general, this is called database normalization and considered a good thing)

Deleting a player is a bigger endeavor. What happens to all the games the player played? Here, a straightforward solution is to not delete the player but simply mark them inactive.

**Comment by climu** [comment]
I am indeed using django admin interface for such tasks.

The consistency issues you are raising are the reason why I didn't want our league admins to manage the league this way. They will have acces to many things that could easily broke our system if misused. 

Felt it was dangerous so I thought about creating some fancy views that would help admins to do so. 

So you are saying it's better to calculate things like number of games or score on every call rather than just storing it in a field ? I feel this would result in heavier pages but I have no experience nor formation so I am all hear.

**Comment by rocqua** [comment]
Writing a function like delete_game() is indeed the way to go forward. [This link](https://docs.djangoproject.com/en/1.10/topics/db/models/#overriding-model-methods) has some ways that you could do this so the function is called when any object is deleted (such as via the admin interface).

I still see your point about the admin interface. I think you are right on writing separate views for that.

**Comment by climu** [comment]
After performing some db normalisation, we decided to keep score field.

Hence I made a signal receiver that update game before deleting a game in this [commit](https://github.com/climu/openstudyroom/commit/7f43f22e531305352fff7266f39d63dff231272e).

Indeed I read [here](http://stackoverflow.com/questions/1534986/how-do-i-override-delete-on-a-model-and-have-it-still-work-with-related-delete) that overriding delete method will not work on bulk delete. So I thought it was safer to use a signal receiver.

We are working on creating some admin views now :)
