### ISSUE TITLE
Allow reverse search of players by OGS/KGS username

### ISSUE THREAD

**Issue by AlexEngelhardt** [climu/openstudyroom#215]
It would be nice to enter someone's KGS username in a search field and get the corresponding OSR profile.

Maybe by adding a 'Find player' form, or by adding the KGS and OGS username in this page:
https://openstudyroom.org/league/players/

**Comment by climu** [comment]
Just noticed that it works at the moment.

I mean you can use the search field in the very page you linked and try typing a OGS username. It works.

That's because the OGS/KGS usernames are inside the username row of this table as a html tooltip. It appear datatables is looking for such content too.

We should still show OGS/KGS usernames in that table tho I think.
