### ISSUE TITLE
Get player results implicitly from DB

### ISSUE THREAD

**Issue by rocqua** [climu/openstudyroom#22]
The current way the results of a player are stored is via a string that stores a serialized dict, that is eval'ed to get the dict back.

As each game has 3 foreign keys to players (black, white and winner) we can generate the very same results dict from the database directly. This means we no-longer have to keep the serialized dicts in sync with the actual played games. (It also closes a security hole where we are eval'ing player names. Those could theoretically contain python code).

Given that we are going to be deleting matches (as per issue #18) this is going to save a lot of time.
A similar thing could be done to LeagePlayer.nb_wins and LeaguePlayer.nb_losses, at which point (I think) we wouldn't need to modify a LeaguePlayer at all when deleting a Game.

The solution would look something like below, this is fully of the cuff, I haven't even checked if it has syntax errors.

from collections import defaultdict

    from collections import defaultdict

    def get_results(self):
        blackGames = self.black.get_queryset() 
        whiteGames = self.black.get_queryset()
        
        resultsDict = defaultdict(list)
        
        for game in blackGames:
            opponent = game.white
            won = game.winner == self
            
            record = {
                'id': game.pk,
                'r' : 1 if won else 0
            }        
            resultsDict[opponent.kgs_username].append(record)
            
        for game in whiteGames:
            opponent = game.black
            won = game.winner == self
            
            record = {
                'id': game.pk,
                'r' : 1 if won else 0
            }        
            resultsDict[opponent.kgs_username].append(record)
            
Should performance ever be an issue, this function could be cached.

**Comment by mlrdk** [comment]
I will take a look at this and see what can be improved later tomorrow. Just to check in.

**Comment by climu** [comment]
Cool !
Let us know.

**Comment by climu** [comment]
I have implemented that locally and it works fine.

I have done same things with nb_win and nb_loss fields.

I have a questions regarding the score field:

We can easily remove this field but then when we get players, we can't sort them by score directly using order_by('-score').

We obviously can sort those in python sorted() but I feel this will uses more of ram.

Do you think we should keep the score field or remove it and we don't care about ram uses ?

Maybe my concern would be right if we had large number of player to sort, but for our max 50 it's not relevent.

**Comment by rocqua** [comment]
Reasons to keep score:
Performance
Convenience

Reasons to remove score:
Handles deleted games better
More 'normalized'

Regarding the handling of deleted games, it's easy if the order of games doesn't matter (e.g. with a flat score per win). You can simply undo the score change. When the order of games does matter (e.g. with an elo system) it becomes much more of a chore.

As we seem to use a flat score change, I think its defensible to keep the score field.

I feel like it's a wash, so not worth spending the time on. When

**Comment by climu** [comment]
Thank you for your answer !
Just saw it and I went to try removing it in the meantime. See [this commit](https://github.com/climu/openstudyroom/commit/3325cb225cc4176a57c09d9b47f5da960b985503).

I like to test things to see how it goes.

It works obviously. However, considering your advices, I will add the score field again.

**Comment by SolarBear** [comment]
I'd argue to remove it. I can't think performance will be much of an issue in our case (in time, we'll have a few hundred games on record, a few thousand tops) so, with proper column indexation, it really shouldn't be a problem. As for convenience, I feel this is the kind of info we should get from an SQL view, not stored in a table.

If some day performance become an issue, I guess upgrading to a full-blown RDBMS like PostgresSQL or MySQL would help; and if that's not enough (one can dream!) having a caching system using something like Redis would help, but let's not get ahead of ourselves, now. ;)

(Real-world example: I had to work on an old .NET app recently that manages car jobs, for instance, and each work day had an entry in the database, but instead of sorting work days by date to determine the beginning and end of the job, it had a `FirstDay` and `LastDay` column. The result: there's a bug (or should I say, _at least one_) where those fields would somehow become out of sync, so the program would be unable to properly determine where jobs began and ended and then became mostly unusable. Getting rid of those columns, sorting by date and adding an index on the date was an easy fix, even with a few hundred thousand entries in the table.)

**Comment by climu** [comment]
hum... I already added the score field back in [this commit](https://github.com/climu/openstudyroom/commit/caae0adc2f96118d63624e6da028de290bafbfd0).

Doubting now.

As for RDBMS , we are using PostgresSQL on production of course :)

I just setted sqlite in local setting file for easy local deployment.

**Comment by SolarBear** [comment]
Your call! I don't think it's a critical issue, though, so it it ever
matters (eg. we start using these fields all around the place) we can
simply refactor it all.

Glad to know we use Postgres in prod, I have one on my machine, this will
allow us some more cool features.

**Comment by climu** [comment]
We decided to keep score for now.

Working on a way to delete games properly now.
