### ISSUE TITLE
how to quit league without leaving community?  

### ISSUE THREAD

**Issue by alexmitrani** [climu/openstudyroom#339]
is there a way for a user to quit a community league without quitting the community?
we have a user who is SDK who enrolled in both monthly league and DDK league
I can't see a way for them to quit the DDK league or for us to remove them.
I looked on django-admin and couldn't see a way of doing it there, either.  
For now I have just asked them not to play DDKs in the DDK league, but it is a bit awkward.  
Thanks.

**Comment by climu** [comment]
A user can quit a league or a community by pressing related buttons:
- On community page, they should have a "quit community" button.
- On leagues pages, they should have a "quit league" that will quit him the league but not the related community. This button will only be shown only if a player didn't played any game in the league.

This can be done in django-admin but we shouldn't use that as it could easily break things.

If there is a need for admins to remove players from a league, I could add buttons for that. This wasn't really needed up to now since users can easily quit a league.

So I am closing the issue for now. I guess the quite league/community process should be documented somewhere.
